export const regions = {
  "Andijon viloyati": [
    "Oltinko'l tumani",
    "Andijon tumani",
    "Baliqchi tumani",
    "Bo'ston tumani",
    "Buloqboshi tumani",
    "Jalaquduq tumani",
    "Izboskan tumani",
    "Ulug'nor tumani",
    "Qo'rg'ontepa tumani",
    "Asaka tumani",
    "Marhamat tumani",
    "Shahrixon tumani",
    "Paxtaobod tumani",
    "Xo'jaobod tumani",
    "Andijon shahri",
    "Xonоbod shahri",
  ],
  "Buxoro viloyati": [
    "Olot tumani",
    "Buxoro tumani",
    "Vobkent tumani",
    "G'ijduvon tumani",
    "Kogon tumani",
    "Qorako'l tumani",
    "Qorovulbozor tumani",
    "Peshko' tumani",
    "Romitan tumani",
    "Jondor tumani",
    "Shofirkon tumani",
    "Buxoro shahri",
    "Kogon shahri",
  ],
  "Jizzax viloyati": [
    "Arnasoy tumani",
    "Baxmal tumani",
    "G'allaorol tumani",
    "Sharof Rashidov tumani",
    "Do'stlik tumani",
    "Zomin tumani",
    "Zarbdor tumani",
    "Mirzacho'l tumani",
    "Zafarobod tumani",
    "Paxtakor tumani",
    "Forish tumani",
    "Yangiobod tumani",
    "Jizzax shahri",
  ],
  "Qashqadaryo viloyati": [
    "G'uzor tumani",
    "Dehqonobod tumani",
    "Qamashi tumani",
    "Qarshi tumani",
    "Koson tumani",
    "Kitob tumani",
    "Mirishkor tumani",
    "Muborak tumani",
    "Nishon tumani",
    "Kasbi tumani",
    "Ko'kdala tumani",
    "Chiroqchi tumani",
    "Shahrisabz tumani",
    "Yakkabog' tumani",
    "Qarshi shahri",
    "Shahrisabz shahri",
  ],
  "Navoiy viloyati": [
    "Konimex tumani",
    "Qiziltepa tumani",
    "Navbahor tumani",
    "Karmana tumani",
    "Nurota tumani",
    "Tomdi tumani",
    "Uchquduq tumani",
    "Xatirchi tumani",
    "Navoiy shahri",
    "Zarafshon shahri",
    "Go'zg'on shahri",
  ],
  "Namangan viloyati": [
    "Mingbuloq tumani",
    "Kosonsoy tumani",
    "Namangan tumani",
    "Norin tumani",
    "Pop tumani",
    "To'raqo'rg'on tumani",
    "Uychi tumani",
    "Uchqo'rg'on tumani",
    "Chortoq tumani",
    "Chust tumani",
    "Yangiqo'rg'on tumani",
    "Namangan shahri",
    "Davlatobod tumani",
    "Yangi Namangan tumani",
  ],
  "Samarqand viloyati": [
    "Oqdaryo tumani",
    "Bulung'ur tumani",
    "Jomboy tumani",
    "Ishtixon tumani",
    "Kattaqo'rg'on tumani",
    "Qo'shrabot tumani",
    "Narpay tumani",
    "Payariq tumani",
    "Pastdarg'om tumani",
    "Paxtachi tumani",
    "Samarqand tumani",
    "Nurobod tumani",
    "Urgut tumani",
    "Tayloq tumani",
    "Samarqand shahri",
    "Kattaqo'rg'on shahri",
  ],
  "Surxondaryo viloyati": [
    "Oltinsoy tumani",
    "Angor tumani",
    "Bandixon tumani",
    "Boysun tumani",
    "Muzrabot tumani",
    "Denov tumani",
    "Jarqo'rg'on tumani",
    "Qumqo'rg'on tumani",
    "Qiziriq tumani",
    "Sariosiyo tumani",
    "Termiz tumani",
    "Uzun tumani",
  ],
  "Sirdaryo viloyati": [
    "Oqoltin tumani",
    "Boyovut tumani",
    "Sayxunobod tumani",
    "Guliston tumani",
    "Sardoba tumani",
    "Mirzaobod tumani",
    "Sirdaryo tumani",
    "Xovos tumani",
    "Guliston shahri",
    "Shirin shahri",
    "Yangiyer shahri",
  ],
  "Toshkent shahri": [
    "Uchtepa tumani",
    "Bektemir tumani",
    "Yunusobod tumani",
    "Mirzo Ulug'bek tumani",
    "Mirobod tumani",
    "Shayxontohur tumani",
    "Olmazor tumani",
    "Sirg'ali tumani",
    "Yakkasaroy tumani",
    "Yashnobod tumani",
    "Yangihayot tumani",
    "Chilonzor tumani",
    "Yangi Toshkent shahri",
  ],
  "Toshkent viloyati": [
    "Oqqo'rg'on tumani",
    "Ohangaron tumani",
    "Bekobod tumani",
    "Bo'stonliq tumani",
    "Bo'ka tumani",
    "Quyichirchiq tumani",
    "Zangiota tumani",
    "Yuqorichirchiq tumani",
    "Qibray tumani",
    "Parkent tumani",
    "Piskent tumani",
    "O'rtachirchiq tumani",
    "Chinoz tumani",
    "Yangiyo'l tumani",
    "Toshkent tumani",
    "Nurafshon shahri",
    "Olmaliq shahri",
    "Angren shahri",
    "Bekobod shahri",
    "Ohangaron shahri",
    "Chirchiq shahri",
    "Yangiyo'l shahri",
  ],
  "Farg'ona viloyati": [
    "Oltiariq tumani",
    "Qo'shtepa tumani",
    "Bag'dod tumani",
    "Buvayda tumani",
    "Beshariq tumani",
    "Quva tumani",
    "Uchko'prik tumani",
    "Rishton tumani",
    "So'x tumani",
    "Toshloq tumani",
    "O'zbekiston tumani",
    "Farg'ona tumani",
    "Dang'ara tumani",
  ],
  "Xorazm viloyati": [
    "Bog'ot tumani",
    "Gurlan tumani",
    "Qo'shko'pir tumani",
    "Urganch tumani",
    "Xazorasp tumani",
    "Tuproqqal'a tumani",
    "Xonqa tumani",
    "Xiva tumani",
    "Shovot tumani",
    "Yangiariq tumani",
    "Yangibozor tumani",
    "Urganch shahri",
    "Xiva shahri",
  ],
  "Qoraqalpog'iston Respublikasi": [
    "Amudaryo tumani",
    "Beruniy tumani",
    "Bo'zatov tumani",
    "Qorao'zak tumani",
    "Kegeyli tumani",
    "Qo'ng'irot tumani",
    "Qonliko'l tumani",
    "Mo'ynoq tumani",
    "Nukus tumani",
    "Taxiatosh tumani",
    "Taxtako'pir tumani",
    "To'rtko'l tumani",
    "Xo'jayli tumani",
    "Chimboy tumani",
    "Shumanay tumani",
    "Ellikqal'a tumani",
    "Nukus shahri",
  ],
};
